#!/usr/bin/env python3
"""
Database migration CLI for VeloZ Gateway.

This script provides a command-line interface for managing database migrations
using Alembic. It supports:
- Running migrations (upgrade/downgrade)
- Creating new migrations
- Checking migration status
- Database initialization

Usage:
    python -m db.migrate upgrade          # Apply all pending migrations
    python -m db.migrate downgrade -1     # Rollback one migration
    python -m db.migrate current          # Show current revision
    python -m db.migrate history          # Show migration history
    python -m db.migrate create "message" # Create new migration
    python -m db.migrate init             # Initialize database
"""

import argparse
import os
import sys
from pathlib import Path

# Ensure the gateway directory is in the path
gateway_dir = Path(__file__).parent.parent
sys.path.insert(0, str(gateway_dir))

from alembic.config import Config
from alembic import command
from alembic.script import ScriptDirectory
from alembic.runtime.migration import MigrationContext
from sqlalchemy import create_engine, text


def get_alembic_config() -> Config:
    """Get Alembic configuration."""
    config_path = gateway_dir / "alembic.ini"
    config = Config(str(config_path))

    # Override database URL from environment if set
    database_url = os.getenv("VELOZ_DATABASE_URL")
    if database_url:
        config.set_main_option("sqlalchemy.url", database_url)

    return config


def get_database_url() -> str:
    """Get database URL from environment or default."""
    return os.getenv("VELOZ_DATABASE_URL", "sqlite:///veloz_gateway.db")


def cmd_upgrade(args):
    """Apply migrations up to a revision."""
    config = get_alembic_config()
    revision = args.revision or "head"
    print(f"Upgrading database to revision: {revision}")
    command.upgrade(config, revision)
    print("Upgrade complete.")


def cmd_downgrade(args):
    """Rollback migrations to a revision."""
    config = get_alembic_config()
    revision = args.revision or "-1"
    print(f"Downgrading database to revision: {revision}")
    command.downgrade(config, revision)
    print("Downgrade complete.")


def cmd_current(args):
    """Show current database revision."""
    config = get_alembic_config()
    print("Current database revision:")
    command.current(config, verbose=True)


def cmd_history(args):
    """Show migration history."""
    config = get_alembic_config()
    print("Migration history:")
    command.history(config, verbose=args.verbose)


def cmd_heads(args):
    """Show available heads."""
    config = get_alembic_config()
    print("Available heads:")
    command.heads(config, verbose=True)


def cmd_create(args):
    """Create a new migration."""
    config = get_alembic_config()
    message = args.message
    autogenerate = args.autogenerate

    if autogenerate:
        print(f"Creating autogenerated migration: {message}")
        command.revision(config, message=message, autogenerate=True)
    else:
        print(f"Creating empty migration: {message}")
        command.revision(config, message=message)

    print("Migration created.")


def cmd_check(args):
    """Check if there are pending migrations."""
    config = get_alembic_config()
    script = ScriptDirectory.from_config(config)

    database_url = get_database_url()
    engine = create_engine(database_url)

    with engine.connect() as conn:
        context = MigrationContext.configure(conn)
        current_rev = context.get_current_revision()

    head_rev = script.get_current_head()

    print(f"Current revision: {current_rev or 'None'}")
    print(f"Head revision:    {head_rev}")

    if current_rev == head_rev:
        print("\nDatabase is up to date.")
        return 0
    else:
        print("\nPending migrations detected!")
        # List pending migrations
        for rev in script.iterate_revisions(head_rev, current_rev):
            if rev.revision != current_rev:
                print(f"  - {rev.revision}: {rev.doc}")
        return 1


def cmd_init(args):
    """Initialize database with all migrations."""
    config = get_alembic_config()

    # Check if database exists and has tables
    database_url = get_database_url()
    engine = create_engine(database_url)

    try:
        with engine.connect() as conn:
            # Check if alembic_version table exists
            result = conn.execute(text(
                "SELECT name FROM sqlite_master WHERE type='table' AND name='alembic_version'"
                if "sqlite" in database_url else
                "SELECT tablename FROM pg_tables WHERE tablename='alembic_version'"
            ))
            has_alembic = result.fetchone() is not None

        if has_alembic and not args.force:
            print("Database already initialized. Use --force to reinitialize.")
            return 1

    except Exception as e:
        print(f"Note: {e}")

    print("Initializing database...")
    command.upgrade(config, "head")
    print("Database initialized successfully.")
    return 0


def cmd_stamp(args):
    """Stamp the database with a specific revision without running migrations."""
    config = get_alembic_config()
    revision = args.revision
    print(f"Stamping database with revision: {revision}")
    command.stamp(config, revision)
    print("Stamp complete.")


def cmd_sql(args):
    """Generate SQL for migrations (offline mode)."""
    config = get_alembic_config()
    start = args.start or "base"
    end = args.end or "head"
    print(f"Generating SQL from {start} to {end}:")
    command.upgrade(config, f"{start}:{end}", sql=True)


def main():
    parser = argparse.ArgumentParser(
        description="VeloZ Gateway Database Migration Tool",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python -m db.migrate upgrade              # Apply all pending migrations
  python -m db.migrate upgrade 20260223_000001  # Upgrade to specific revision
  python -m db.migrate downgrade -1         # Rollback one migration
  python -m db.migrate downgrade base       # Rollback all migrations
  python -m db.migrate current              # Show current revision
  python -m db.migrate history              # Show migration history
  python -m db.migrate check                # Check for pending migrations
  python -m db.migrate create "Add new table"   # Create empty migration
  python -m db.migrate create "Add new table" --autogenerate  # Auto-generate migration
  python -m db.migrate init                 # Initialize database
  python -m db.migrate sql                  # Generate SQL script

Environment Variables:
  VELOZ_DATABASE_URL    Database connection URL (default: sqlite:///veloz_gateway.db)
                        Examples:
                          sqlite:///veloz_gateway.db
                          postgresql://user:pass@localhost/veloz
"""
    )

    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # upgrade
    upgrade_parser = subparsers.add_parser("upgrade", help="Apply migrations")
    upgrade_parser.add_argument("revision", nargs="?", default="head",
                                help="Target revision (default: head)")
    upgrade_parser.set_defaults(func=cmd_upgrade)

    # downgrade
    downgrade_parser = subparsers.add_parser("downgrade", help="Rollback migrations")
    downgrade_parser.add_argument("revision", nargs="?", default="-1",
                                  help="Target revision (default: -1)")
    downgrade_parser.set_defaults(func=cmd_downgrade)

    # current
    current_parser = subparsers.add_parser("current", help="Show current revision")
    current_parser.set_defaults(func=cmd_current)

    # history
    history_parser = subparsers.add_parser("history", help="Show migration history")
    history_parser.add_argument("-v", "--verbose", action="store_true",
                                help="Show detailed history")
    history_parser.set_defaults(func=cmd_history)

    # heads
    heads_parser = subparsers.add_parser("heads", help="Show available heads")
    heads_parser.set_defaults(func=cmd_heads)

    # create
    create_parser = subparsers.add_parser("create", help="Create new migration")
    create_parser.add_argument("message", help="Migration description")
    create_parser.add_argument("--autogenerate", "-a", action="store_true",
                               help="Auto-generate migration from model changes")
    create_parser.set_defaults(func=cmd_create)

    # check
    check_parser = subparsers.add_parser("check", help="Check for pending migrations")
    check_parser.set_defaults(func=cmd_check)

    # init
    init_parser = subparsers.add_parser("init", help="Initialize database")
    init_parser.add_argument("--force", "-f", action="store_true",
                             help="Force reinitialization")
    init_parser.set_defaults(func=cmd_init)

    # stamp
    stamp_parser = subparsers.add_parser("stamp", help="Stamp database with revision")
    stamp_parser.add_argument("revision", help="Revision to stamp")
    stamp_parser.set_defaults(func=cmd_stamp)

    # sql
    sql_parser = subparsers.add_parser("sql", help="Generate SQL script")
    sql_parser.add_argument("--start", "-s", default="base",
                            help="Start revision (default: base)")
    sql_parser.add_argument("--end", "-e", default="head",
                            help="End revision (default: head)")
    sql_parser.set_defaults(func=cmd_sql)

    args = parser.parse_args()

    if args.command is None:
        parser.print_help()
        return 1

    # Change to gateway directory for Alembic
    os.chdir(gateway_dir)

    return args.func(args) or 0


if __name__ == "__main__":
    sys.exit(main())
